kind: Service
apiVersion: v1
metadata:
  name: consumer-service
  labels:
    name: consumer-service
    app: kafka
spec:
  ports:
    - nodePort: 30082 
      port: 8384     
      targetPort: 8384  
      protocol: TCP
  selector:           
    app: consumer-service
    app: kafka
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: consumer-service
spec:                
  selector:         
    matchLabels:
      app: consumer-service
      app: kafka
  replicas: 1        
  template:
    metadata:
      labels:        
        app: consumer-service
        app: kafka
    spec:
      containers:
        - name: consumer-service
          image: talk2me19/consumer-service:v1
          ports:
            - containerPort: 8384                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     